### ISSUE TITLE
Create updated landing page

### ISSUE THREAD

**Issue by ryangoree** [delvtech/delv-website#1]
**Prototype:** https://www.figma.com/proto/YunSPY65lv6T39BTdqdrtg/Delv-Handoff?type=design&node-id=2323-7923&t=qLWLtM5ufdSi0Dw2-1&scaling=min-zoom&page-id=2129%3A4674&starting-point-node-id=2323%3A7923&show-proto-sidebar=1&mode=design

**Figma:** https://www.figma.com/file/YunSPY65lv6T39BTdqdrtg/Delv-Handoff?type=design&node-id=2323%3A9766&mode=design&t=RXiQT3BMlwXOkXAP-1

**Requirments Doc:** https://www.notion.so/delv-tech/DELV-website-requirements-29ecdb9412054238a4c4f54b9f6d0f24?pvs=4

**Deployment:** https://delvtech.github.io/delv-landing-page/

**Comment by ryangoree** [comment]
On hold for:

- [x] Mobile layout mocks
- [x] Final content
- [x] "Build" link staying? Where should it link to?
- [x] Design review

**Comment by ryangoree** [comment]
Build link is being replaced with the GitHub Link.

- [ ] ~Remove "Build" menu link (GitHub link already exists)~

**Comment by ryangoree** [comment]
- [x] Increase logo sizes in drawers where it makes sense and polish layout, spacing
- [x] Social links are awkwardly placed over project tiles, find new location if possible
- [x] Change Element website href to the docs page (https://docs.element.fi/)
- [x] Remove Hyperdrive website button for now
- [x] Change Values to 2 cols
- [x] Unbold first sentences in Guiding Principles
- [x] Change body font color in Values and Guiding principles
- [x] Change Build href to github
- [ ] ~Change to hash router (attempting to access a route directly results 404)~
- [x] Add terms link to the bottom of the menu (https://elementfi.s3.us-east-2.amazonaws.com/element-finance-terms-of-service.pdf)
- [x] Shrink header on scroll

**Comment by akhamisa** [comment]
Hey Ryan, Dispatch has provided mobile designs for the website. Seems like everything is essentially a squeezed river page. Nothing groundbreaking, pretty straight forward:
https://www.figma.com/file/YunSPY65lv6T39BTdqdrtg/Delv-Handoff?type=design&node-id=563%3A2&mode=design&t=o47aYtze5g2staCB-1

**Comment by ryangoree** [comment]
All changes and responsive layouts implemented. Just waiting for approval on the terms link placement.
